# XC7A100T-FGG484 physical IO constraints for nuc_event_gen_10mcps_io_top.
# clk/rst_n are fixed by board request. DAC outputs are kept together in Bank13.

create_clock -name clk -period 4.000 [get_ports clk]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

set_property PACKAGE_PIN R4 [get_ports clk]
set_property PACKAGE_PIN U7 [get_ports rst_n]

set_property IOSTANDARD LVCMOS33 [get_ports {clk rst_n cfg_valid cfg_write cfg_addr[*] cfg_wdata[*] cfg_rdata[*] cfg_ready amp_lut_we amp_lut_addr[*] amp_lut_wdata[*] dac_sample_vec[*] dac_sample_valid}]
set_property PULLUP true [get_ports rst_n]
set_false_path -from [get_ports rst_n]

# DAC output bus, Bank13
set_property PACKAGE_PIN AA10 [get_ports {dac_sample_vec[0]}]
set_property PACKAGE_PIN AA11 [get_ports {dac_sample_vec[1]}]
set_property PACKAGE_PIN AA13 [get_ports {dac_sample_vec[2]}]
set_property PACKAGE_PIN AA14 [get_ports {dac_sample_vec[3]}]
set_property PACKAGE_PIN AA15 [get_ports {dac_sample_vec[4]}]
set_property PACKAGE_PIN AA16 [get_ports {dac_sample_vec[5]}]
set_property PACKAGE_PIN AA9  [get_ports {dac_sample_vec[6]}]
set_property PACKAGE_PIN AB10 [get_ports {dac_sample_vec[7]}]
set_property PACKAGE_PIN AB11 [get_ports {dac_sample_vec[8]}]
set_property PACKAGE_PIN AB12 [get_ports {dac_sample_vec[9]}]
set_property PACKAGE_PIN AB13 [get_ports {dac_sample_vec[10]}]
set_property PACKAGE_PIN AB15 [get_ports {dac_sample_vec[11]}]
set_property PACKAGE_PIN AB16 [get_ports {dac_sample_vec[12]}]
set_property PACKAGE_PIN AB17 [get_ports {dac_sample_vec[13]}]
set_property PACKAGE_PIN T14  [get_ports {dac_sample_vec[14]}]
set_property PACKAGE_PIN T15  [get_ports {dac_sample_vec[15]}]
set_property PACKAGE_PIN T16  [get_ports dac_sample_valid]

# Configuration write bus, Bank15
set_property PACKAGE_PIN G13 [get_ports cfg_valid]
set_property PACKAGE_PIN G15 [get_ports cfg_write]
set_property PACKAGE_PIN G16 [get_ports {cfg_addr[0]}]
set_property PACKAGE_PIN G17 [get_ports {cfg_addr[1]}]
set_property PACKAGE_PIN G18 [get_ports {cfg_addr[2]}]
set_property PACKAGE_PIN G20 [get_ports {cfg_addr[3]}]
set_property PACKAGE_PIN H13 [get_ports {cfg_addr[4]}]
set_property PACKAGE_PIN H14 [get_ports {cfg_addr[5]}]
set_property PACKAGE_PIN H15 [get_ports {cfg_addr[6]}]
set_property PACKAGE_PIN H17 [get_ports {cfg_addr[7]}]
set_property PACKAGE_PIN H18 [get_ports {cfg_wdata[0]}]
set_property PACKAGE_PIN H19 [get_ports {cfg_wdata[1]}]
set_property PACKAGE_PIN H20 [get_ports {cfg_wdata[2]}]
set_property PACKAGE_PIN H22 [get_ports {cfg_wdata[3]}]
set_property PACKAGE_PIN J14 [get_ports {cfg_wdata[4]}]
set_property PACKAGE_PIN J15 [get_ports {cfg_wdata[5]}]
set_property PACKAGE_PIN J16 [get_ports {cfg_wdata[6]}]
set_property PACKAGE_PIN J17 [get_ports {cfg_wdata[7]}]
set_property PACKAGE_PIN J19 [get_ports {cfg_wdata[8]}]
set_property PACKAGE_PIN J20 [get_ports {cfg_wdata[9]}]
set_property PACKAGE_PIN J21 [get_ports {cfg_wdata[10]}]
set_property PACKAGE_PIN J22 [get_ports {cfg_wdata[11]}]
set_property PACKAGE_PIN K13 [get_ports {cfg_wdata[12]}]
set_property PACKAGE_PIN K14 [get_ports {cfg_wdata[13]}]
set_property PACKAGE_PIN K16 [get_ports {cfg_wdata[14]}]
set_property PACKAGE_PIN K17 [get_ports {cfg_wdata[15]}]
set_property PACKAGE_PIN K18 [get_ports {cfg_wdata[16]}]
set_property PACKAGE_PIN K19 [get_ports {cfg_wdata[17]}]
set_property PACKAGE_PIN K21 [get_ports {cfg_wdata[18]}]
set_property PACKAGE_PIN K22 [get_ports {cfg_wdata[19]}]
set_property PACKAGE_PIN L13 [get_ports {cfg_wdata[20]}]
set_property PACKAGE_PIN L14 [get_ports {cfg_wdata[21]}]
set_property PACKAGE_PIN L15 [get_ports {cfg_wdata[22]}]
set_property PACKAGE_PIN L16 [get_ports {cfg_wdata[23]}]
set_property PACKAGE_PIN L18 [get_ports {cfg_wdata[24]}]
set_property PACKAGE_PIN L19 [get_ports {cfg_wdata[25]}]
set_property PACKAGE_PIN L20 [get_ports {cfg_wdata[26]}]
set_property PACKAGE_PIN L21 [get_ports {cfg_wdata[27]}]
set_property PACKAGE_PIN M13 [get_ports {cfg_wdata[28]}]
set_property PACKAGE_PIN M15 [get_ports {cfg_wdata[29]}]
set_property PACKAGE_PIN M16 [get_ports {cfg_wdata[30]}]
set_property PACKAGE_PIN M17 [get_ports {cfg_wdata[31]}]

# Configuration readback bus, Bank16
set_property PACKAGE_PIN A13 [get_ports {cfg_rdata[0]}]
set_property PACKAGE_PIN A14 [get_ports {cfg_rdata[1]}]
set_property PACKAGE_PIN A15 [get_ports {cfg_rdata[2]}]
set_property PACKAGE_PIN A16 [get_ports {cfg_rdata[3]}]
set_property PACKAGE_PIN A18 [get_ports {cfg_rdata[4]}]
set_property PACKAGE_PIN A19 [get_ports {cfg_rdata[5]}]
set_property PACKAGE_PIN A20 [get_ports {cfg_rdata[6]}]
set_property PACKAGE_PIN A21 [get_ports {cfg_rdata[7]}]
set_property PACKAGE_PIN B13 [get_ports {cfg_rdata[8]}]
set_property PACKAGE_PIN B15 [get_ports {cfg_rdata[9]}]
set_property PACKAGE_PIN B16 [get_ports {cfg_rdata[10]}]
set_property PACKAGE_PIN B17 [get_ports {cfg_rdata[11]}]
set_property PACKAGE_PIN B18 [get_ports {cfg_rdata[12]}]
set_property PACKAGE_PIN B20 [get_ports {cfg_rdata[13]}]
set_property PACKAGE_PIN B21 [get_ports {cfg_rdata[14]}]
set_property PACKAGE_PIN B22 [get_ports {cfg_rdata[15]}]
set_property PACKAGE_PIN C13 [get_ports {cfg_rdata[16]}]
set_property PACKAGE_PIN C14 [get_ports {cfg_rdata[17]}]
set_property PACKAGE_PIN C15 [get_ports {cfg_rdata[18]}]
set_property PACKAGE_PIN C17 [get_ports {cfg_rdata[19]}]
set_property PACKAGE_PIN C18 [get_ports {cfg_rdata[20]}]
set_property PACKAGE_PIN C19 [get_ports {cfg_rdata[21]}]
set_property PACKAGE_PIN C20 [get_ports {cfg_rdata[22]}]
set_property PACKAGE_PIN C22 [get_ports {cfg_rdata[23]}]
set_property PACKAGE_PIN D14 [get_ports {cfg_rdata[24]}]
set_property PACKAGE_PIN D15 [get_ports {cfg_rdata[25]}]
set_property PACKAGE_PIN D16 [get_ports {cfg_rdata[26]}]
set_property PACKAGE_PIN D17 [get_ports {cfg_rdata[27]}]
set_property PACKAGE_PIN D19 [get_ports {cfg_rdata[28]}]
set_property PACKAGE_PIN D20 [get_ports {cfg_rdata[29]}]
set_property PACKAGE_PIN D21 [get_ports {cfg_rdata[30]}]
set_property PACKAGE_PIN D22 [get_ports {cfg_rdata[31]}]
set_property PACKAGE_PIN E13 [get_ports cfg_ready]

# ICDF amplitude LUT write port, Bank34
set_property PACKAGE_PIN AA1 [get_ports amp_lut_we]
set_property PACKAGE_PIN AA3 [get_ports {amp_lut_addr[0]}]
set_property PACKAGE_PIN AA4 [get_ports {amp_lut_addr[1]}]
set_property PACKAGE_PIN AA5 [get_ports {amp_lut_addr[2]}]
set_property PACKAGE_PIN AA6 [get_ports {amp_lut_addr[3]}]
set_property PACKAGE_PIN AA8 [get_ports {amp_lut_addr[4]}]
set_property PACKAGE_PIN AB1 [get_ports {amp_lut_addr[5]}]
set_property PACKAGE_PIN AB2 [get_ports {amp_lut_addr[6]}]
set_property PACKAGE_PIN AB3 [get_ports {amp_lut_addr[7]}]
set_property PACKAGE_PIN AB5 [get_ports {amp_lut_addr[8]}]
set_property PACKAGE_PIN AB6 [get_ports {amp_lut_addr[9]}]
set_property PACKAGE_PIN AB7 [get_ports {amp_lut_addr[10]}]
set_property PACKAGE_PIN AB8 [get_ports {amp_lut_addr[11]}]
set_property PACKAGE_PIN R2  [get_ports {amp_lut_addr[12]}]
set_property PACKAGE_PIN R3  [get_ports {amp_lut_addr[13]}]
set_property PACKAGE_PIN R6  [get_ports {amp_lut_wdata[0]}]
set_property PACKAGE_PIN T1  [get_ports {amp_lut_wdata[1]}]
set_property PACKAGE_PIN T4  [get_ports {amp_lut_wdata[2]}]
set_property PACKAGE_PIN T5  [get_ports {amp_lut_wdata[3]}]
set_property PACKAGE_PIN T6  [get_ports {amp_lut_wdata[4]}]
set_property PACKAGE_PIN U1  [get_ports {amp_lut_wdata[5]}]
set_property PACKAGE_PIN U2  [get_ports {amp_lut_wdata[6]}]
set_property PACKAGE_PIN U3  [get_ports {amp_lut_wdata[7]}]
set_property PACKAGE_PIN U5  [get_ports {amp_lut_wdata[8]}]
set_property PACKAGE_PIN U6  [get_ports {amp_lut_wdata[9]}]
set_property PACKAGE_PIN V2  [get_ports {amp_lut_wdata[10]}]
set_property PACKAGE_PIN V3  [get_ports {amp_lut_wdata[11]}]
set_property PACKAGE_PIN V4  [get_ports {amp_lut_wdata[12]}]
set_property PACKAGE_PIN V5  [get_ports {amp_lut_wdata[13]}]
set_property PACKAGE_PIN V7  [get_ports {amp_lut_wdata[14]}]
set_property PACKAGE_PIN V8  [get_ports {amp_lut_wdata[15]}]
